// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFiles(arg1:string,arg2:number,arg3:number):Promise<main.FileList>;

export function Greet(arg1:string):Promise<string>;

export function Mkdir(arg1:string):Promise<boolean>;

export function Remove(arg1:string):Promise<boolean>;

export function Rename(arg1:string,arg2:string):Promise<boolean>;
